//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probnyjj
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Год.
    /// </summary>
    // *** Start programmer edit section *** (Год CustomAttributes)

    // *** End programmer edit section *** (Год CustomAttributes)
    public enum Год
    {
        
        // *** Start programmer edit section *** (Год.2000 CustomAttributes)

        // *** End programmer edit section *** (Год.2000 CustomAttributes)
        2000,
        
        // *** Start programmer edit section *** (Год.2002 CustomAttributes)

        // *** End programmer edit section *** (Год.2002 CustomAttributes)
        2002,
    }
}
